def module4():
    # module 4a
    # basic motion
    # are these provided waypoints are within reach of the robot?
    # move from one to the other and back
    # -------------------------------
    waypt1 = p[0.2,-0.15,0.25,0,3.14159,0]
    waypt2 = p[0.2,-0.15,0.45,0,3.14159,0]
    def m4a():
      movej(waypt1)
      movel(waypt2)
      movel(waypt1)
    end
    
    m4a()

    # -------------------------------
    # module 4b
    # pose manipulation
    # make new waypoint varables that are 150mm in positive base X from the provided waypoints
    # move to all 4 waypoints, using a blend radius where possible
    # -------------------------------
    def m4b():
      offset=p[0.15,0,0,0,0,0]
      waypt3=pose_add(waypt2,offset)
      waypt4=pose_add(waypt1,offset)
      movel(waypt1)
      movel(waypt2)
      movel(waypt3)
      movel(waypt4)
      movel(waypt1)
      movel(waypt2, r=0.05)
      movel(waypt3, r=0.05)
      movel(waypt4, r=0.05)
      movel(waypt1)
    end
    m4b()


    # -------------------------------
    # module 4c
    # movep
    # create a list of 6 waypoints, then use a for loop to movep() to each of them
    # -------------------------------
    
    def m4c():
      p1 = waypt1
      p2 = waypt2
      p3 = waypt3
      p4 = waypt4
      p5 = pose_add(waypt4, p[0,-0.1,0.1,0,0,0])
      p6 = pose_add(waypt1, p[0,-0.1,0.1,0,0,0])
      waypt_list = [p1, p2, p3, p4, p5, p6]
      local i=0
      while i < waypt_list.length():
          movep(waypt_list[i],r=0.025)
          i=i+1
          if (i==waypt_list.length()):
            stopl(1.5)
          end
      end
    end

    # -------------------------------
    # module 4d
    # optimove
    # move to the waypoints from 4b using optimovel() and then again with optimovej()
    # -------------------------------
    def m4d():
      acc=0.25
      vel=0.25
      optimovel(waypt1, a=acc, v=vel)
      optimovel(waypt2, a=acc, v=vel, r=0.05)
      optimovel(waypt3, a=acc, v=vel, r=0.05)
      optimovel(waypt4, a=acc, v=vel, r=0.05)
      optimovel(waypt1)

      optimovej(waypt1, a=acc, v=vel)
      optimovej(waypt2, a=acc, v=vel, r=0.05)
      optimovej(waypt3, a=acc, v=vel, r=0.05)
      optimovej(waypt4, a=acc, v=vel, r=0.05)
      optimovej(waypt1, a=acc, v=vel)
    end
    m4d()
    
    # -------------------------------
    # module 4e
    # the waypoint below does not point straight down
    # move to a waypont that is 50mm above it
    # move to a waypont that is 50mm in the tool negative z direction from it
    # -------------------------------
    rotated_pt = p[0,-0.15,0.25,0.1,3.03,0.9]

    def m4e():
      z_up = p[0,0,0.05,0,0,0]
      pt_up = pose_add(rotated_pt,z_up)
      z_retract = p[0,0,-0.05,0,0,0]
      pt_retract = pose_trans(rotated_pt,z_retract)
      movej(rotated_pt)
      movel(pt_up)
      movel(rotated_pt)
      movel(pt_retract)
    end
    m4e()
    


    # -------------------------------
    # module 4f
    # write a function to convert from pose to list, and another to convert back
    # ex: pose_to_list(p[0.1,0.2,0.3,0,0,3.14]) -> [0.1,0.2,0.3,0,0,3.14]
    #     list_to_pose([0.1,0.2,0.3,0,0,3.14]) -> p[0.1,0.2,0.3,0,0,3.14]
    # use a for loop
    # -------------------------------
    def pose_to_list(pose_arg):
        local i=0
        tmp_ans = make_list(6,0,0)
        while i < 6:
            tmp_ans[i] = pose_arg[i]
            i=i+1
        end
        return tmp_ans
    end
    
    def list_to_pose(list_arg):
      tmp_ans = p[0,0,0,0,0,0]
      local i=0
      while i < 6:
        tmp_ans[i] = list_arg[i]
        i=i+1
      end
    end
    # test the functions
    def m4f():
      test_pose = p[0.1,0.2,0.3,0,0,3.14]
      pose_as_list = pose_to_list(test_pose)
      popup("pose as list: "+to_str(pose_as_list), blocking=True)
      list_as_pose = list_to_pose(pose_as_list)
      popup("list as pose: "+to_str(list_as_pose), blocking=True)
    end
    m4f()
    # -------------------------------

end
























