def module3():
    # module 3a
    # structs and lists
    # Create a variable length list of integers
    # prompt the user to enter integers, and then ask if they want to add another, looping until the user says no
    # display the result in a popup
    # -------------------------------
    def m3a():


    # -------------------------------
    # module 3b
    # display the results of the list back to user, one entry at a time
    # -------------------------------
 

    # -------------------------------
    # module 3c
    # display the result of the list back to the user, two entries at a time
    # -------------------------------
  

    # -------------------------------
    # module 3d
    # make a struct describing a workpiece blank - SKU#, l/w/h, weight
    # display the struct back to the user
    # -------------------------------

   

    # -------------------------------
    # module 3e
    # make a varable length list of workpiece structs
    # display the number of workpieces in the list, and the total weight of all workpieces
    # -------------------------------
 


    # -------------------------------
    # module 3f
    # FIFO (first in, first out) lists
    # create a variable length list with a capacity of 10 integers
    # prompt the user to enter 4 items
    # then, make a loop that executes 5 times
    # in each pass of the loop:
    # - remove the first item in the list
    # - prompt the user to enter a new item to go at the end of list 
    # - display the current value of the list 
    # -------------------------------
    

    # -------------------------------

end 
















