def module4():
    # module 4a
    # basic motion
    # are these provided waypoints are within reach of the robot?
    # move from one to the other and back
    # -------------------------------
    waypt1 = p[0.2,-0.15,0.25,0,3.14159,0]
    waypt2 = p[0.2,-0.15,0.45,0,3.14159,0]
    

    # -------------------------------
    # module 4b
    # pose manipulation
    # make new waypoint varables that are 150mm in positive base X from the provided waypoints
    # move to all 4 waypoints, using a blend radius where possible
    # -------------------------------



    # -------------------------------
    # module 4c
    # movep
    # create a list of 6 waypoints, then use a for loop to movep() to each of them
    # -------------------------------
    


    # -------------------------------
    # module 4d
    # optimove
    # move to the waypoints from 4b using optimovel() and then again with optimovej()
    # -------------------------------
 
    
    # -------------------------------
    # module 4e
    # the waypoint below does not point straight down
    # move to a waypont that is 50mm above it
    # move to a waypont that is 50mm in the tool negative z direction from it
    # -------------------------------
    rotated_pt = p[0,-0.15,0.25,0.1,3.03,0.9]

    


    # -------------------------------
    # module 4f
    # write a function to convert from pose to list, and another to convert back
    # ex: pose_to_list(p[0.1,0.2,0.3,0,0,3.14]) -> [0.1,0.2,0.3,0,0,3.14]
    #     list_to_pose([0.1,0.2,0.3,0,0,3.14]) -> p[0.1,0.2,0.3,0,0,3.14]
    # use a for loop
    # -------------------------------

    
    # -------------------------------

end
























