# module 1a
# basics of a functions
# create a function, and use it on the robot
# function should be named max_of_two, have two arguments, and return the largest value
# -----------------------------


# -----------------------------
# module 1b
# create a function that calls another function
# function should be named max_of_three(), have three arguments, and return the largest value
# -----------------------------


# -----------------------------



